# Lesson 4: 문장 임베딩

In [18]:
!pip install -q sentence-transformers

In [19]:
from transformers.utils import logging
logging.set_verbosity_error()

### 🤗 Transformers 라이브러리를 사용하여 '문장 임베딩' 파이프라인을 구축

In [20]:
from sentence_transformers import SentenceTransformer

git clone https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2

In [24]:
model = SentenceTransformer("./models/all-MiniLM-L6-v2")
# model = SentenceTransformer("all-MiniLM-L6-v2")

More info on [all-MiniLM-L6-v2](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2).

In [25]:
sentences1 = ['The cat sits outside',
              'A man is playing guitar',
              'The movies are awesome']

In [26]:
embeddings1 = model.encode(sentences1, convert_to_tensor=True)

In [27]:
embeddings1

tensor([[ 0.1392,  0.0030,  0.0470,  ...,  0.0641, -0.0163,  0.0636],
        [ 0.0227, -0.0014, -0.0056,  ..., -0.0225,  0.0846, -0.0283],
        [-0.1043, -0.0628,  0.0093,  ...,  0.0020,  0.0653, -0.0150]])

In [28]:
embeddings1.shape

torch.Size([3, 384])

In [29]:
sentences2 = ['The dog plays in the garden',
              'A woman watches TV',
              'The new movie is so great']

In [30]:
embeddings2 = model.encode(sentences2, 
                           convert_to_tensor=True)

In [31]:
print(embeddings2)

tensor([[ 0.0163, -0.0700,  0.0384,  ...,  0.0447,  0.0254, -0.0023],
        [ 0.0054, -0.0920,  0.0140,  ...,  0.0167, -0.0086, -0.0424],
        [-0.0842, -0.0592, -0.0010,  ..., -0.0157,  0.0764,  0.0389]])


* 두 문장 사이의 코사인 유사도를 계산하여 서로 얼마나 유사한지 측정합니다.

In [32]:
from sentence_transformers import util

In [33]:
cosine_scores = util.cos_sim(embeddings1, embeddings2)

In [34]:
print(cosine_scores)

tensor([[ 0.2838,  0.1310, -0.0029],
        [ 0.2277, -0.0327, -0.0136],
        [-0.0124, -0.0465,  0.6571]])


In [35]:
for i in range(len(sentences1)):
    print("{} \t\t {} \t\t Score: {:.4f}".format(sentences1[i],
                                                 sentences2[i],
                                                 cosine_scores[i][i]))

The cat sits outside 		 The dog plays in the garden 		 Score: 0.2838
A man is playing guitar 		 A woman watches TV 		 Score: -0.0327
The movies are awesome 		 The new movie is so great 		 Score: 0.6571


### Try it yourself! 
- Try this model with your own sentences!